# This file is auto-generated by OpenAPI Generator (https://openapi-generator.tech)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'Org.OpenAPITools CategoryApi' {
    Context 'CategoryApi' {
        It 'Invoke-CategoryApiCategory' {
            $ret = Invoke-PetApiGetPetById -key "TEST_VALUE" -domain "TEST_VALUE" -category "TEST_VALUE" -parents "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
