#import <Foundation/Foundation.h>
#import "OAICategory.h"
#import "OAIApi.h"

/**
* Keepa API
* The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
*
* OpenAPI spec version: 1.0.0
* Contact: info@keepa.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/



@interface OAICategoryApi: NSObject <OAIApi>

extern NSString* kOAICategoryApiErrorDomain;
extern NSInteger kOAICategoryApiMissingParamErrorCode;

-(instancetype) initWithApiClient:(OAIApiClient *)apiClient NS_DESIGNATED_INITIALIZER;

/// Returns Amazon category information from Keepa API.
/// Retrieve category objects using their node ids and (optional) their parent tree.
///
/// @param key Your private API key.
/// @param domain Integer value for the Amazon locale you want to access. (1-com, 2-co.uk, 3-de, 4-fr, 5-co.jp, 6-ca, 7-cn, 8-it, 9-es, 10-in, 11-com.mx, 12-com.br, 13-com.au)
/// @param category The category node id of the category you want to request. For batch requests a comma separated list of ids (up to 10, the token cost stays the same). Alternatively you can specify the value 0, which will retrieve a list of all root categories.
/// @param parents Whether or not to include the category tree for each category. (1 &#x3D; include, 0 &#x3D; do not include.)
/// 
///  code:200 message:"search results matching criteria",
///  code:400 message:"bad input parameter"
///
/// @return NSArray<OAICategory>*
-(NSURLSessionTask*) categoryWithKey: (NSString*) key
    domain: (NSNumber*) domain
    category: (NSNumber*) category
    parents: (NSNumber*) parents
    completionHandler: (void (^)(NSArray<OAICategory>* output, NSError* error)) handler;



@end
