/**
 * Keepa API
 * The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@keepa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 *
 * OpenAPI Generator version: 4.0.0-beta2
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.KeepaApi);
  }
}(this, function(expect, KeepaApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new KeepaApi.Category();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Category', function() {
    it('should create an instance of Category', function() {
      // uncomment below and update the code to test Category
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be.a(KeepaApi.Category);
    });

    it('should have the property domainId (base name: "domainId")', function() {
      // uncomment below and update the code to test the property domainId
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

    it('should have the property catId (base name: "catId")', function() {
      // uncomment below and update the code to test the property catId
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

    it('should have the property children (base name: "children")', function() {
      // uncomment below and update the code to test the property children
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

    it('should have the property parent (base name: "parent")', function() {
      // uncomment below and update the code to test the property parent
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

    it('should have the property highestRank (base name: "highestRank")', function() {
      // uncomment below and update the code to test the property highestRank
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

    it('should have the property productCount (base name: "productCount")', function() {
      // uncomment below and update the code to test the property productCount
      //var instance = new KeepaApi.Category();
      //expect(instance).to.be();
    });

  });

}));
