# Keepa API
#
# The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
#
# OpenAPI spec version: 1.0.0
# Contact: info@keepa.com
# Generated by: https://openapi-generator.tech


#' Category Class
#'
#' @field domainId 
#' @field catId 
#' @field name 
#' @field children 
#' @field parent 
#' @field highestRank 
#' @field productCount 
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Category <- R6::R6Class(
  'Category',
  public = list(
    `domainId` = NULL,
    `catId` = NULL,
    `name` = NULL,
    `children` = NULL,
    `parent` = NULL,
    `highestRank` = NULL,
    `productCount` = NULL,
    initialize = function(`domainId`, `catId`, `name`, `children`, `parent`, `highestRank`, `productCount`){
      if (!missing(`domainId`)) {
                stopifnot(is.numeric(`domainId`), length(`domainId`) == 1)
        self$`domainId` <- `domainId`
      }
      if (!missing(`catId`)) {
                stopifnot(is.numeric(`catId`), length(`catId`) == 1)
        self$`catId` <- `catId`
      }
      if (!missing(`name`)) {
                stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`children`)) {
                stopifnot(is.vector(`children`), length(`children`) != 0)
                sapply(`children`, function(x) stopifnot(is.character(x)))
        self$`children` <- `children`
      }
      if (!missing(`parent`)) {
                stopifnot(is.numeric(`parent`), length(`parent`) == 1)
        self$`parent` <- `parent`
      }
      if (!missing(`highestRank`)) {
                stopifnot(is.numeric(`highestRank`), length(`highestRank`) == 1)
        self$`highestRank` <- `highestRank`
      }
      if (!missing(`productCount`)) {
                stopifnot(is.numeric(`productCount`), length(`productCount`) == 1)
        self$`productCount` <- `productCount`
      }
    },
    toJSON = function() {
      CategoryObject <- list()
      if (!is.null(self$`domainId`)) {
        CategoryObject[['domainId']] <-
                self$`domainId`
      }
      if (!is.null(self$`catId`)) {
        CategoryObject[['catId']] <-
                self$`catId`
      }
      if (!is.null(self$`name`)) {
        CategoryObject[['name']] <-
                self$`name`
      }
      if (!is.null(self$`children`)) {
        CategoryObject[['children']] <-
                self$`children`
      }
      if (!is.null(self$`parent`)) {
        CategoryObject[['parent']] <-
                self$`parent`
      }
      if (!is.null(self$`highestRank`)) {
        CategoryObject[['highestRank']] <-
                self$`highestRank`
      }
      if (!is.null(self$`productCount`)) {
        CategoryObject[['productCount']] <-
                self$`productCount`
      }

      CategoryObject
    },
    fromJSON = function(CategoryJson) {
      CategoryObject <- jsonlite::fromJSON(CategoryJson)
      if (!is.null(CategoryObject$`domainId`)) {
                self$`domainId` <- CategoryObject$`domainId`
      }
      if (!is.null(CategoryObject$`catId`)) {
                self$`catId` <- CategoryObject$`catId`
      }
      if (!is.null(CategoryObject$`name`)) {
                self$`name` <- CategoryObject$`name`
      }
      if (!is.null(CategoryObject$`children`)) {
                self$`children` <- CategoryObject$`children`
      }
      if (!is.null(CategoryObject$`parent`)) {
                self$`parent` <- CategoryObject$`parent`
      }
      if (!is.null(CategoryObject$`highestRank`)) {
                self$`highestRank` <- CategoryObject$`highestRank`
      }
      if (!is.null(CategoryObject$`productCount`)) {
                self$`productCount` <- CategoryObject$`productCount`
      }
    },
    toJSONString = function() {
       outstring <- sprintf(
        '{
           "domainId":
                      %d
                      
                  
              ,
           "catId":
                      %d
                      
                  
              ,
           "name":
                      
                      "%s"
                  
              ,
           "children":
                      
                      ["%s"]
                  
              ,
           "parent":
                      %d
                      
                  
              ,
           "highestRank":
                      %d
                      
                  
              ,
           "productCount":
                      %d
                      
                  
              
        }',
                self$`domainId`,
                self$`catId`,
                self$`name`,
                paste0(self$`children`, collapse='","'),
                self$`parent`,
                self$`highestRank`,
                self$`productCount`
      )
      gsub("[\r\n]| ", "", outstring)
    },
    fromJSONString = function(CategoryJson) {
      CategoryObject <- jsonlite::fromJSON(CategoryJson)
              self$`domainId` <- CategoryObject$`domainId`
              self$`catId` <- CategoryObject$`catId`
              self$`name` <- CategoryObject$`name`
              self$`children` <- CategoryObject$`children`
              self$`parent` <- CategoryObject$`parent`
              self$`highestRank` <- CategoryObject$`highestRank`
              self$`productCount` <- CategoryObject$`productCount`
    }
  )
)
