--  Keepa API
--  The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep_Alive connection.  Multiple requests can be made in parallel to increase throughput.
--
--  OpenAPI spec version: 1.0.0
--  Contact: info@keepa.com
--
--  NOTE: This package is auto generated by the swagger code generator 4.0.0-beta2.
--  https://openapi-generator.tech
--  Do not edit the class manually.
with Swagger.Streams;
with Ada.Containers.Vectors;
package .Models is



   type CategoryType is
     record
       Domain_Id : Integer;
       Cat_Id : Integer;
       Name : Swagger.UString;
       Children : Integer_Vectors.Vector;
       Parent : Integer;
       Highest_Rank : Integer;
       Product_Count : Integer;
     end record;

   package CategoryType_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => CategoryType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in CategoryType);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in CategoryType_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out CategoryType);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out CategoryType_Vectors.Vector);



end .Models;
