{-
   Keepa API
   The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.

   OpenAPI spec version: 1.0.0
   Contact: info@keepa.com

   NOTE: This file is auto generated by the openapi-generator.
   https://github.com/openapitools/openapi-generator.git
   Do not edit this file manually.
-}


module Request.Product exposing (product)

import Data.Category as Category exposing (Category)
import Dict
import Http
import Json.Decode as Decode
import Url.Builder as Url


basePath : String
basePath =
    "https://virtserver.swaggerhub.com/magicCashew/keepa/1.0.0"


{-| Retrieves the product object for the specified ASIN and domain. If our last update is older than one hour it will be automatically refreshed before delivered to you to ensure you get near to real-time pricing data.  You can request products via either their ASIN (preferred) or via UPC and EAN codes. You can not use both parameters, asin and code, in the same request. Keepa can not track Amazon Fresh and eBooks.
-}
product :
    { onSend : Result Http.Error (List Category) -> msg




    , key : String    , domain : Int    , asin : Maybe (String)    , code : Maybe (String)
    }
    -> Cmd msg
product params =
    Http.request
        { method = "GET"
        , headers = []
        , url = Url.crossOrigin basePath
            ["product"]
            (List.filterMap identity [Just (Url.string "key"  params.key), Just (Url.string "domain" <| String.fromInt params.domain), Maybe.map (Url.string "asin" ) params.asin, Maybe.map (Url.string "code" ) params.code])
        , body = Http.emptyBody
        , expect = Http.expectJson params.onSend (Decode.list Category.decoder)
        , timeout = Just 30000
        , tracker = Nothing
        }
