Articus\PathHandler\RouteInjection\Factory:
  paths:
    '/magicCashew/keepa/1.0.0':
    - App\Handler\Category
    - App\Handler\Product
  handlers:
    abstract_factories:
    - Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory
#  consumers:
#    factories:
#    invokables:
#  attributes:
#    factories:
#    invokables:
#  producers:
#    factories:
#    invokables:

Zend\ServiceManager\AbstractFactory\ConfigAbstractFactory:
  App\Handler\Category: []
  App\Handler\Product: []
