/**
* Keepa API
* The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
*
* OpenAPI spec version: 1.0.0
* Contact: info@keepa.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

#include "CategoryApi.h"
#include "Helpers.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::helpers;
using namespace org::openapitools::server::model;

CategoryApi::CategoryApi(std::shared_ptr<Pistache::Rest::Router> rtr) { 
    router = rtr;
};

void CategoryApi::init() {
    setupRoutes();
}

void CategoryApi::setupRoutes() {
    using namespace Pistache::Rest;

    Routes::Get(*router, base + "/category", Routes::bind(&CategoryApi::category_handler, this));

    // Default handler, called when a route is not found
    router->addCustomHandler(Routes::bind(&CategoryApi::category_api_default_handler, this));
}

void CategoryApi::category_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {

    // Getting the query params
    auto keyQuery = request.query().get("key");
    Pistache::Optional<std::string> key;
    if(!keyQuery.isEmpty()){
        std::string value;
        if(fromStringValue(keyQuery.get(), value)){
            key = Pistache::Some(value);
        }
    }
    auto domainQuery = request.query().get("domain");
    Pistache::Optional<int32_t> domain;
    if(!domainQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(domainQuery.get(), value)){
            domain = Pistache::Some(value);
        }
    }
    auto categoryQuery = request.query().get("category");
    Pistache::Optional<int32_t> category;
    if(!categoryQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(categoryQuery.get(), value)){
            category = Pistache::Some(value);
        }
    }
    auto parentsQuery = request.query().get("parents");
    Pistache::Optional<int32_t> parents;
    if(!parentsQuery.isEmpty()){
        int32_t value;
        if(fromStringValue(parentsQuery.get(), value)){
            parents = Pistache::Some(value);
        }
    }
    
    try {
      this->category(key, domain, category, parents, response);
    } catch (std::runtime_error & e) {
      //send a 400 error
      response.send(Pistache::Http::Code::Bad_Request, e.what());
      return;
    }

}

void CategoryApi::category_api_default_handler(const Pistache::Rest::Request &request, Pistache::Http::ResponseWriter response) {
    response.send(Pistache::Http::Code::Not_Found, "The requested method does not exist");
}

}
}
}
}

