--  Keepa API
--  The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep_Alive connection.  Multiple requests can be made in parallel to increase throughput.
--
--  OpenAPI spec version: 1.0.0
--  Contact: info@keepa.com
--
--  NOTE: This package is auto generated by the swagger code generator 4.0.0-beta2.
--  https://openapi-generator.tech
--  Do not edit the class manually.
with .Models;
with Swagger.Clients;
package .Clients is

   type Client_Type is new Swagger.Clients.Client_Type with null record;

   --  Returns Amazon category information from Keepa API.
   --  Retrieve category objects using their node ids and (optional) their parent tree.
   procedure Category
      (Client : in out Client_Type;
       Key : in Swagger.UString;
       Domain : in Integer;
       Category : in Integer;
       Parents : in Integer;
       Result : out .Models.CategoryType_Vectors.Vector);

   --  Retrieve the product for the specified ASIN and domain.
   --  Retrieves the product object for the specified ASIN and domain. If our last update is older than one hour it will be automatically refreshed before delivered to you to ensure you get near to real-time pricing data.  You can request products via either their ASIN (preferred) or via UPC and EAN codes. You can not use both parameters, asin and code, in the same request. Keepa can not track Amazon Fresh and eBooks.
   procedure Product
      (Client : in out Client_Type;
       Key : in Swagger.UString;
       Domain : in Integer;
       Asin : in Swagger.Nullable_UString;
       Code : in Swagger.Nullable_UString;
       Result : out .Models.CategoryType_Vectors.Vector);

end .Clients;
