--[[
  Keepa API
 
  The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 
  OpenAPI spec version: 1.0.0
  Contact: info@keepa.com
  Generated by: https://openapi-generator.tech
]]

-- category class
local category = {}
local category_mt = {
	__name = "category";
	__index = category;
}

local function cast_category(t)
	return setmetatable(t, category_mt)
end

local function new_category(domain_id, cat_id, name, children, parent, highest_rank, product_count)
	return cast_category({
		["domainId"] = domain_id;
		["catId"] = cat_id;
		["name"] = name;
		["children"] = children;
		["parent"] = parent;
		["highestRank"] = highest_rank;
		["productCount"] = product_count;
	})
end

return {
	cast = cast_category;
	new = new_category;
}
