# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule KeepaAPI.Model.Category do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"domainId",
    :"catId",
    :"name",
    :"children",
    :"parent",
    :"highestRank",
    :"productCount"
  ]

  @type t :: %__MODULE__{
    :"domainId" => integer(),
    :"catId" => integer(),
    :"name" => String.t,
    :"children" => [integer()],
    :"parent" => integer(),
    :"highestRank" => integer(),
    :"productCount" => integer()
  }
end

defimpl Poison.Decoder, for: KeepaAPI.Model.Category do
  def decode(value, _options) do
    value
  end
end

