// tslint:disable
/**
 * Keepa API
 * The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@keepa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Observable } from 'rxjs';
import { BaseAPI, RequiredError, HttpHeaders, HttpQuery, COLLECTION_FORMATS } from '../runtime';
import {
    Category,
} from '../models';

export interface ProductRequest {
    key: string;
    domain: ProductDomainEnum;
    asin?: string;
    code?: string;
}

/**
 * no description
 */
export class ProductApi extends BaseAPI {

    /**
     * Retrieves the product object for the specified ASIN and domain. If our last update is older than one hour it will be automatically refreshed before delivered to you to ensure you get near to real-time pricing data.  You can request products via either their ASIN (preferred) or via UPC and EAN codes. You can not use both parameters, asin and code, in the same request. Keepa can not track Amazon Fresh and eBooks.
     * Retrieve the product for the specified ASIN and domain.
     */
    productRaw(requestParameters: ProductRequest): Observable<Array<Category>> {
        if (requestParameters.key === null || requestParameters.key === undefined) {
            throw new RequiredError('key','Required parameter requestParameters.key was null or undefined when calling product.');
        }

        if (requestParameters.domain === null || requestParameters.domain === undefined) {
            throw new RequiredError('domain','Required parameter requestParameters.domain was null or undefined when calling product.');
        }

        const queryParameters: HttpQuery = {};

        if (requestParameters.key !== undefined && requestParameters.key !== null) {
            queryParameters['key'] = requestParameters.key;
        }

        if (requestParameters.domain !== undefined && requestParameters.domain !== null) {
            queryParameters['domain'] = requestParameters.domain;
        }

        if (requestParameters.asin !== undefined && requestParameters.asin !== null) {
            queryParameters['asin'] = requestParameters.asin;
        }

        if (requestParameters.code !== undefined && requestParameters.code !== null) {
            queryParameters['code'] = requestParameters.code;
        }

        const headerParameters: HttpHeaders = {};

        return this.request<Array<Category>>({
            path: `/product`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        });
    }

    /**
     * Retrieves the product object for the specified ASIN and domain. If our last update is older than one hour it will be automatically refreshed before delivered to you to ensure you get near to real-time pricing data.  You can request products via either their ASIN (preferred) or via UPC and EAN codes. You can not use both parameters, asin and code, in the same request. Keepa can not track Amazon Fresh and eBooks.
     * Retrieve the product for the specified ASIN and domain.
     */
    product(requestParameters: ProductRequest): Observable<Array<Category>> {
        return this.productRaw(requestParameters);
    }

}

/**
    * @export
    * @enum {string}
    */
export enum ProductDomainEnum {
    NUMBER_1 = 1,
    NUMBER_2 = 2,
    NUMBER_3 = 3,
    NUMBER_4 = 4,
    NUMBER_5 = 5,
    NUMBER_6 = 6,
    NUMBER_7 = 7,
    NUMBER_8 = 8,
    NUMBER_9 = 9,
    NUMBER_10 = 10,
    NUMBER_11 = 11,
    NUMBER_12 = 12,
    NUMBER_13 = 13
}
