<?php

/**
 * Keepa API
 * The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@keepa.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > swagger-codegen/modules/swagger-codegen/src/main/resources/php-laravel/
 */


namespace App\Http\Controllers;

use Illuminate\Support\Facades\Request;

class CategoryController extends Controller
{
    /**
     * Constructor
     */
    public function __construct()
    {
    }

    /**
     * Operation category
     *
     * Returns Amazon category information from Keepa API..
     *
     *
     * @return Http response
     */
    public function category()
    {
        $input = Request::all();

        //path params validation


        //not path params validation
        if (!isset($input['key'])) {
            throw new \InvalidArgumentException('Missing the required parameter $key when calling category');
        }
        $key = $input['key'];

        if (!isset($input['domain'])) {
            throw new \InvalidArgumentException('Missing the required parameter $domain when calling category');
        }
        $domain = $input['domain'];

        if (!isset($input['category'])) {
            throw new \InvalidArgumentException('Missing the required parameter $category when calling category');
        }
        $category = $input['category'];

        if (!isset($input['parents'])) {
            throw new \InvalidArgumentException('Missing the required parameter $parents when calling category');
        }
        $parents = $input['parents'];


        return response('How about implementing category as a get method ?');
    }
}
