--[[
  Keepa API
 
  The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 
  OpenAPI spec version: 1.0.0
  Contact: info@keepa.com
  Generated by: https://openapi-generator.tech
]]

--[[
Unit tests for openapiclient.api.category_api
Automatically generated by openapi-generator (https://openapi-generator.tech)
Please update as you see appropriate
]]
describe("category_api", function()
  local openapiclient_category_api = require "openapiclient.api.category_api"
  -- unit tests for category
  describe("category test", function()
    it("should work", function()
      -- TODO assertion here: http://olivinelabs.com/busted/#asserts
    end)
  end)

end)
