/**
* Keepa API
* The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
*
* OpenAPI spec version: 1.0.0
* Contact: info@keepa.com
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/

/*
* CategoryApiImpl.h
*
* 
*/

#ifndef CATEGORY_API_IMPL_H_
#define CATEGORY_API_IMPL_H_


#include <pistache/endpoint.h>
#include <pistache/http.h>
#include <pistache/router.h>
#include <memory>

#include <CategoryApi.h>

#include <pistache/optional.h>

#include "Category.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class CategoryApiImpl : public org::openapitools::server::api::CategoryApi {
public:
    CategoryApiImpl(std::shared_ptr<Pistache::Rest::Router>);
    ~CategoryApiImpl() {}

    void category(const Pistache::Optional<std::string> &key, const Pistache::Optional<int32_t> &domain, const Pistache::Optional<int32_t> &category, const Pistache::Optional<int32_t> &parents, Pistache::Http::ResponseWriter &response);

};

}
}
}
}



#endif