/**
 * Keepa API
 * The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@keepa.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#ifndef OAI_OAIProductApi_H
#define OAI_OAIProductApi_H

#include "OAIHttpRequest.h"

#include "OAICategory.h"
#include <QString>

#include <QObject>

namespace OpenAPI {

class OAIProductApi: public QObject {
    Q_OBJECT

public:
    OAIProductApi();
    OAIProductApi(QString host, QString basePath);
    ~OAIProductApi();

    QString host;
    QString basePath;
    QMap<QString, QString> defaultHeaders;

    void product(const QString& key, const qint32& domain, const QString& asin, const QString& code);
    
private:
    void productCallback (OAIHttpRequestWorker * worker);
    
signals:
    void productSignal(QList<OAICategory> summary);
    
    void productSignalFull(OAIHttpRequestWorker* worker, QList<OAICategory> summary);
    
    void productSignalE(QList<OAICategory> summary, QNetworkReply::NetworkError error_type, QString& error_str);
    
    void productSignalEFull(OAIHttpRequestWorker* worker, QNetworkReply::NetworkError error_type, QString& error_str);
    
};

}
#endif
