/**
 * Keepa API
 * The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@keepa.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/*
 * CategoryApi.h
 *
 * 
 */

#ifndef CategoryApi_H_
#define CategoryApi_H_


#include <memory>
#include <corvusoft/restbed/session.hpp>
#include <corvusoft/restbed/resource.hpp>
#include <corvusoft/restbed/service.hpp>

#include "Category.h"
#include <string>

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

class  CategoryApi: public restbed::Service
{
public:
	CategoryApi();
	~CategoryApi();
	void startService(int const& port);
	void stopService();
};


/// <summary>
/// Returns Amazon category information from Keepa API.
/// </summary>
/// <remarks>
/// Retrieve category objects using their node ids and (optional) their parent tree.
/// </remarks>
class  CategoryApiCategoryResource: public restbed::Resource
{
public:
	CategoryApiCategoryResource();
    virtual ~CategoryApiCategoryResource();
    void GET_method_handler(const std::shared_ptr<restbed::Session> session);
};


}
}
}
}

#endif /* CategoryApi_H_ */

