/**
 * Keepa API
 * The Keepa API offers numerous endpoints.  Every request requires your API access key as a parameter. You can find and change your key in the keepa portal. All requests must be issued as a HTTPS GET and accept gzip encoding. If possible, use a Keep-Alive connection.  Multiple requests can be made in parallel to increase throughput.
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@keepa.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator 4.0.0-beta2.
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


#include <corvusoft/restbed/byte.hpp>
#include <corvusoft/restbed/string.hpp>
#include <corvusoft/restbed/settings.hpp>
#include <corvusoft/restbed/request.hpp>

#include "ProductApi.h"

namespace org {
namespace openapitools {
namespace server {
namespace api {

using namespace org::openapitools::server::model;

ProductApi::ProductApi() {
	std::shared_ptr<ProductApiProductResource> spProductApiProductResource = std::make_shared<ProductApiProductResource>();
	this->publish(spProductApiProductResource);
	
}

ProductApi::~ProductApi() {}

void ProductApi::startService(int const& port) {
	std::shared_ptr<restbed::Settings> settings = std::make_shared<restbed::Settings>();
	settings->set_port(port);
	settings->set_root("/magicCashew/keepa/1.0.0");
	
	this->start(settings);
}

void ProductApi::stopService() {
	this->stop();
}

ProductApiProductResource::ProductApiProductResource()
{
	this->set_path("/product/");
	this->set_method_handler("GET",
		std::bind(&ProductApiProductResource::GET_method_handler, this,
			std::placeholders::_1));
}

ProductApiProductResource::~ProductApiProductResource()
{
}

void ProductApiProductResource::GET_method_handler(const std::shared_ptr<restbed::Session> session) {

	const auto request = session->get_request();
			
			
			// Getting the query params
			const std::string key = request->get_query_parameter("key", "");
			const int32_t domain = request->get_query_parameter("domain", 0);
			const std::string asin = request->get_query_parameter("asin", "");
			const std::string code = request->get_query_parameter("code", "");

			
			// Change the value of this variable to the appropriate response before sending the response
			int status_code = 200;
			
			/**
			 * Process the received information here
			 */
			
			if (status_code == 200) {
				session->close(200, "search results matching criteria", { {"Connection", "close"} });
				return;
			}
			if (status_code == 400) {
				session->close(400, "bad input parameter", { {"Connection", "close"} });
				return;
			}

}




}
}
}
}

